# -*- coding: utf-8 -*-
"""CVlab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ev2iGHHlTCr9PmvafouYVuvtVVUGwgUG
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np

def show_comparison(original,blur3,blur5,blur7):
  plt.figure(figsize=(12,10))
  #
  plt.subplot(2,2,1)
  plt.imshow(original,cmap='gray')
  plt.title('Original Grayscale Image')
  plt.axis('off')
  #
  plt.subplot(2,2,2)
  plt.imshow(blur3,cmap='gray')
  plt.title('Average Fliter(3x3)')
  plt.axis('off')
  #
  plt.subplot(2,2,3)
  plt.imshow(blur5,cmap='gray')
  plt.title('Average Fliter(5x5)')
  plt.axis('off')
  #
  plt.subplot(2,2,4)
  plt.imshow(blur7,cmap='gray')
  plt.title('Average Fliter(7x7)')
  plt.axis('off')

  plt.tight_layout()
  plt.show()

img=cv2.imread('parrot.jpg',0)
if img is None:
    print('Error loading image')
    exit()

plt.imshow(img, cmap='gray')
plt.title('Loaded Image: parrot.jpg')
plt.axis('off')
plt.show()

blur3 = cv2.blur(img,(3,3))
blur5 = cv2.blur(img,(5,5))
blur7 = cv2.blur(img,(7,7))

show_comparison(img,blur3,blur5,blur7)

import cv2
img=cv2.imread('nature.jpg',0)
if img is None:
    print('Error loading image')
    exit()

import matplotlib.pyplot as plt
plt.imshow(img, cmap='gray')
plt.title('Loaded Image: nature.jpg')
plt.axis('off')
plt.show()

blur3 = cv2.blur(img,(3,3))
blur5 = cv2.blur(img,(5,5))
blur7 = cv2.blur(img,(7,7))

import matplotlib.pyplot as plt

def show_comparison(original,blur3,blur5,blur7):
  plt.figure(figsize=(12,10))
  #
  plt.subplot(2,2,1)
  plt.imshow(original,cmap='gray')
  plt.title('Original Grayscale Image')
  plt.axis('off')
  #
  plt.subplot(2,2,2)
  plt.imshow(blur3,cmap='gray')
  plt.title('Average Fliter(3x3)')
  plt.axis('off')
  #
  plt.subplot(2,2,3)
  plt.imshow(blur5,cmap='gray')
  plt.title('Average Fliter(5x5)')
  plt.axis('off')
  #
  plt.subplot(2,2,4)
  plt.imshow(blur7,cmap='gray')
  plt.title('Average Fliter(7x7)')
  plt.axis('off')

  plt.tight_layout()
  plt.show()

show_comparison(img,blur3,blur5,blur7)

import numpy as np
kernel = np.ones((5,5),np.float32)/25

dst = cv2.filter2D(img,-1,kernel)
show_comparison(img,dst,dst,dst)

